/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.remote.web.component.uad.display;

import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.remote.web.component.model.RemoteWebComponentEntry;
import com.liferay.remote.web.component.service.RemoteWebComponentEntryLocalService;
import com.liferay.remote.web.component.uad.constants.RemoteWebComponentUADConstants;
import com.liferay.user.associated.data.display.BaseModelUADDisplay;

import java.io.Serializable;

import java.util.List;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the RemoteWebComponentEntry UAD display.
 *
 * <p>
 * This implementation exists only as a container for the default methods
 * generated by ServiceBuilder. All custom methods should be put in
 * {@link RemoteWebComponentEntryUADDisplay}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @generated
 */
public abstract class BaseRemoteWebComponentEntryUADDisplay
	extends BaseModelUADDisplay<RemoteWebComponentEntry> {

	@Override
	public RemoteWebComponentEntry get(Serializable primaryKey)
		throws PortalException {

		return remoteWebComponentEntryLocalService.getRemoteWebComponentEntry(
			Long.valueOf(primaryKey.toString()));
	}

	@Override
	public String[] getDisplayFieldNames() {
		return new String[] {"name", "url"};
	}

	@Override
	public Class<RemoteWebComponentEntry> getTypeClass() {
		return RemoteWebComponentEntry.class;
	}

	@Override
	protected long doCount(DynamicQuery dynamicQuery) {
		return remoteWebComponentEntryLocalService.dynamicQueryCount(
			dynamicQuery);
	}

	@Override
	protected DynamicQuery doGetDynamicQuery() {
		return remoteWebComponentEntryLocalService.dynamicQuery();
	}

	@Override
	protected List<RemoteWebComponentEntry> doGetRange(
		DynamicQuery dynamicQuery, int start, int end) {

		return remoteWebComponentEntryLocalService.dynamicQuery(
			dynamicQuery, start, end);
	}

	@Override
	protected String[] doGetUserIdFieldNames() {
		return RemoteWebComponentUADConstants.
			USER_ID_FIELD_NAMES_REMOTE_WEB_COMPONENT_ENTRY;
	}

	@Reference
	protected RemoteWebComponentEntryLocalService
		remoteWebComponentEntryLocalService;

}